# Generated by Django 4.2.3 on 2023-08-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='megamenu',
            name='name',
            field=models.CharField(default='mega', max_length=255, null=True),
        ),
    ]
