# Generated by Django 4.2.3 on 2023-08-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamenu', '0003_alter_megamenu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='megamenu',
            name='megaitems',
            field=models.ManyToManyField(to='megamenu.menuitem'),
        ),
    ]
