# Generated by Django 4.2.3 on 2023-08-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='content',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='email',
        ),
    ]
