# Generated by Django 4.2.3 on 2023-08-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.SlugField(max_length=255),
        ),
    ]
