# Generated by Django 4.2.3 on 2023-08-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
